from __future__ import annotations

# Fallback guidance only for fields whose Swagger description is empty or merely
# repeats the field name. Specific Swagger descriptions always take precedence.
FIELD_HINTS: dict[str, str] = {
    "metadata": "Additional metadata associated with the request or returned object.",
    "backend": "Backend name or backend type to use.",
    "echo": "Whether generated output should include the original prompt when supported.",
    "frequency_penalty": "Penalty that reduces repeated use of tokens based on how often they already appeared.",
    "grammar_json_functions": "Backend-specific JSON grammar or function-calling grammar configuration.",
    "ignore_eos": "Whether generation should ignore the model's end-of-sequence token.",
    "min_p": "Minimum-probability sampling threshold used by compatible generation backends.",
    "model_base_name": "Base model name associated with this model or backend configuration.",
    "n_keep": "Number of initial prompt tokens to preserve when the context is shifted or recycled.",
    "negative_prompt": "Text describing content the generator should avoid.",
    "negative_prompt_scale": "Strength applied to the negative prompt when supported by the selected model.",
    "presence_penalty": "Penalty that discourages tokens that have already appeared in the generated context.",
    "reasoning_effort": "Requested reasoning-effort level for models that support this control.",
    "repeat_last_n": "How many recent tokens are considered when applying repetition penalties.",
    "repeat_penalty": "Penalty applied to recently repeated tokens; backend support and scale may vary.",
    "rope_freq_base": "Backend-specific RoPE frequency-base override for compatible language models.",
    "rope_freq_scale": "Backend-specific RoPE frequency-scale override for compatible language models.",
    "step": "Backend-specific generation or processing step value.",
    "tfz": "Backend-specific sampling parameter named `tfz`; consult the selected backend if tuning it.",
    "typical_p": "Typical-sampling probability threshold for compatible generation backends.",
    "store": "Whether LocalAI should retain the generated response when that API supports stored responses.",
    "img": "Image input or image reference used by this operation.",
    "img1": "First image input used for comparison or verification.",
    "img2": "Second image input used for comparison or verification.",
    "anti_spoofing": "Whether to enable anti-spoofing checks for the biometric operation when supported.",
    "created_at": "Creation timestamp.",
    "updated_at": "Last-update timestamp.",
    "labels": "Labels associated with the object or training/routing examples.",
    "context_size": "Maximum context size configured for the model/backend.",
    "gpu_layers": "Number of model layers to offload to GPU when supported by the backend.",
    "kv_quant_bits": "Requested KV-cache quantization bit width when supported by the backend.",
    "entries": "Entries to add, process, or return for this operation.",
    "description": "Human-readable description.",
    "icon": "Icon value or icon reference.",
    "license": "License identifier or license metadata.",
    "tags": "Tags associated with the object.",
    "url": "URL associated with the requested resource.",
    "urls": "URLs associated with the requested resources.",
    "stop_sequences": "Text sequences that should stop generation when encountered.",
    "system": "System-level instruction or prompt supplied to the model.",
    "documents": "Candidate documents or text items to rank against the query.",
    "query": "Query text used to rank or retrieve candidate items.",
    "top_n": "Maximum number of highest-ranked results to return.",
    "instructions": "High-level instructions that guide response generation.",
    "max_output_tokens": "Maximum number of output tokens the model may generate.",
    "previous_response_id": "ID of a previous stored response to continue or reference when supported.",
    "bpm": "Target tempo in beats per minute for generated music when supported.",
    "caption": "Text description or caption conditioning the generated media.",
    "do_sample": "Whether the backend should sample rather than use deterministic token selection.",
    "keyscale": "Musical key or scale conditioning for generated music when supported.",
    "lyrics": "Lyrics used to condition generated music or vocals.",
    "model_id": "Identifier of the target model.",
    "prompt_influence": "Backend-specific strength controlling how strongly the prompt influences generation.",
    "timesignature": "Musical time signature used to condition generated music when supported.",
    "vocal_language": "Language hint for generated vocals.",
    "audio1": "First audio input used for speaker comparison or verification.",
    "audio2": "Second audio input used for speaker comparison or verification.",
}
